---
title: "Getting Started" 
author: "<h4>Authors: <i>`r auths <- eval(parse(text = gsub('person','c',read.dcf('../DESCRIPTION', fields = 'Authors@R'))));paste(auths[names(auths)=='given'],auths[names(auths)=='family'], collapse = ', ')`</i></h4>" 
date: "<h4>Vignette updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{templateR} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup}
library(downloadR) 
```


# Download file

## Multi-threaded  

Generic function for downloading files with a variety of methods, including multi-threaded downloading of a single file with [`axel`](https://github.com/axel-download-accelerator/axel).  

```{r}
input_url <- "https://github.com/RajLabMSSM/echolocatoR/raw/master/data/BST1.rda"
out_path <- downloadR::downloader(input_url = input_url,
                                  download_method = "axel")

dat <- downloadR::load_rdata(out_path)
```

## Single-threaded


```{r}
out_path <- downloadR::downloader(input_url = input_url,
                                  download_method = "wget")

dat <- downloadR::load_rdata(out_path)
```


# Download VCF

More specialized downloading function for Variant Call Format (VCF) files that downloads both the VCF and its index file (if available).

```{r}
vcf_url <- "https://gwas.mrcieu.ac.uk/files/ieu-a-298/ieu-a-298.vcf.gz"
out_paths <- downloadR::download_vcf(vcf_url = vcf_url)
```


# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

